### ISSUE TITLE
Cordova 5.2.0で動作しない

### ISSUE THREAD

**Issue by masahirotanaka** [reproio/repro-cordova-plugin#13]
現在Monacaの組み込みを進めていますが、Cordova 5.2.0を前提とした環境ではビルドに失敗することが分かりました。

確認したところ、下記ファイル:

https://github.com/reproio/repro-cordova-plugin/blob/master/src/android/update_application_name.js

にて使われている

`context.requireCordovaModule('cordova-common')`

がCordova CLI 5.2.0環境下では存在しないことが原因のようです。
Cordova 5.2.0でも動作するように修正して頂くことは出来ませんでしょうか。

またこの内容を見る限り、`<application>`タグの`android.name`に値をセットしておりますが、Monacaではデフォルトでここは空白になっているため、`io.repro.android.CordovaApplication`がセットされることになると思います。こちらについて、特に問題ないか教えて頂けると幸いです。

@takuyaW 補足がありましたらお願いします。

**Comment by morou** [comment]
@masahirotanaka ご連絡ありがとうございます！Cordova 5.2.0でも動作させるための修正はしばらくお待ち下さい。

>またこの内容を見る限り、<application>タグのandroid.nameに値をセットしておりますが、Monacaではデフォルトでここは空白になっているため、io.repro.android.CordovaApplicationがセットされることになると思います。こちらについて、特に問題ないか教えて頂けると幸いです。

問題ありません。といいますのも、ReproのCordova Pluginを利用するためには、ApplicationクラスのonCreateからReproのAPIを呼び出す必要があり、ここで指定している `io.repro.android.CordovaApplication` はこのAPI呼び出しを予め実装したApplicationクラスだからです。

**Comment by morou** [comment]
@masahirotanaka Cordova 5.2.0でも動作するよう修正し、repro-cordova-plugin 2.0.1としてリリースしました。Monaca環境で動作するかご確認よろしくお願いいたします。

**Comment by takuyaW** [comment]
@morou Cordova5.2.0への修正対応ありがとうございました。
Monacaにて動作確認が完了いたしましたので、本日、Monacaへの反映を実施いたします。よろしくお願いいたします。
